version: 2.1

jobs:

  toxify:
      docker:
        - image: fkrull/multi-python

      steps:
        - checkout
        - run: pip install tox
        - run: tox -e << parameters.etox >>




workflows:
  version: 2

  myproj:
    jobs:
      - toxify:
          etox: 'style'

