version: 2.1

jobs:

  toxify:
      docker:
        - image: fkrull/multi-python

      parameters:
        tox_env:
          type: string

      steps:
        - checkout
        - run: python3 -m venv venv
        - run: . venv/bin/activate
        - run: pip install tox
        - run: tox -e << parameters.tox_env >>

workflows:
  version: 2

  myproj:
    jobs:
      - toxify:
          tox_env: 'style'

