version: 2.1

jobs:

  tox:
      docker:
        - image: fkrull/multi-python

      parameters:
        tox_env:
          type: string

      steps:
        - checkout
        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install tox
        - run:
            name: run tox environment '<< parameters.tox_env >>'
            command: |
              . venv/bin/activate
              tox -e << parameters.tox_env >>

workflows:
  version: 2

  CI:
    jobs:
      - tox:
          tox_env: 'style'
      - tox:
          tox_env: 'docstyle'
