version: 2.1

jobs:

  toxify:
      docker:
        - image: fkrull/multi-python

      parameters:
        tox_env:
          type: string

      steps:
        - checkout
        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install tox
        - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox -e << parameters.tox_env >>

workflows:
  version: 2

  myproj:
    jobs:
      - toxify:
          tox_env: 'style'

