# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build SDIST

on:
  - push

  # release:   # ESTO DEBERIA SER EL TRIGGER REAL
  #   types: [created]

jobs:
  testing:
    uses: quatrope/scikit-criteria/.github/workflows/CI.yml@7cb124ef948df09fc32f2cf627f03c51c02ac241
  sdist:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
      run: |
        python setup.py sdist
