# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: Scikit-Criteria

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version: [3.9]
        tox_env:
          - style
          - docstyle
          - check-manifest
          - check-testdir
          - check-headers
          - py39
          - coverage

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py_version}}
      - name: Install tox
        run: pip install tox
      - name: tox -e ${{ matrix.tox_env }}
        run: tox -re ${{ matrix.tox_env }}