# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: Build

on:
  - push
  - pull_request

env:
  default-python: 3.9
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  testing:
    uses: quatrope/scikit-criteria/.github/workflows/tests.yml@${{ BRANCH_NAME }}