# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: Build

on:
  - push
  - pull_request

env:
  default-python: 3.9

jobs:
  testing:
    uses: quatrope/scikit-criteria/.github/workflows/tests.yml@627598d02678656aa5ef82a63b1f468e62456e56